export type CreativeItem = {
  id: string
  type: 'image' | 'video'
  src: string
  poster?: string
  caption: string
  captionVi: string
  model: string
  duration?: string
  language?: 'vi' | 'en' | 'fil' | 'none'
  rating?: number
}

export const HANDMADE_CREATIVE: CreativeItem[] = [
  {
    id: 'gece-1',
    type: 'image',
    src: '/images/gece/1.png',
    caption: 'GECE Group brand identity design piece.',
    captionVi: 'Thiết kế nhận diện thương hiệu GECE Group.',
    model: 'Photoshop, Illustrator + AI',
  },
  {
    id: 'gece-tot-nghiep',
    type: 'image',
    src: '/images/gece/tot nghiep ko so that nghiep.png',
    caption: '"Tốt nghiệp không sợ thất nghiệp" campaign key visual.',
    captionVi: 'Key visual chiến dịch "Tốt nghiệp không sợ thất nghiệp".',
    model: 'Photoshop, Illustrator + AI',
  },
  {
    id: 'gece-pa1',
    type: 'image',
    src: '/images/gece/PA1.png',
    caption: 'GECE Group advertising key visual.',
    captionVi: 'Key visual quảng cáo GECE Group.',
    model: 'Photoshop, Illustrator + AI',
  },
  {
    id: 'gece-1-2',
    type: 'image',
    src: '/images/gece/1.2.png',
    caption: 'GECE Group editorial design piece.',
    captionVi: 'Thiết kế editorial GECE Group.',
    model: 'Photoshop, Illustrator + AI',
  },
  {
    id: 'gece-1-1',
    type: 'image',
    src: '/images/gece/1_1.png',
    caption: 'GECE Group event material design.',
    captionVi: 'Thiết kế tài liệu sự kiện GECE Group.',
    model: 'Photoshop, Illustrator + AI',
  },
]

export const AI_GENERATIVE: CreativeItem[] = [
  {
    id: 'ai-fnb-poster',
    type: 'image',
    src: '/images/creative/fnb-promotion-poster.jpg',
    caption: 'F&B promotion poster generated end-to-end by an AI agent pipeline.',
    captionVi: 'Poster quảng cáo F&B do hệ thống AI Agent tạo hoàn chỉnh.',
    model: 'GPT-Image-2',
  },
  {
    id: 'ai-cellphones-ads',
    type: 'image',
    src: '/images/creative/cellphones-promotion-ads.jpg',
    caption: 'Cellphone store promotional ad generated by AI agents.',
    captionVi: 'Ảnh quảng cáo cửa hàng điện thoại do AI Agent tạo.',
    model: 'GPT-Image-2',
  },
]

export const COMMERCIAL_VIDEOS: CreativeItem[] = [
  {
    id: 'commercial-be-tvc',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/be-tvc.mp4',
    poster: '/images/creative/be-tvc-poster.jpg',
    caption: "TVC-style commercial spot for 'Bé' produced with AI video generation.",
    captionVi: "TVC quảng cáo cho 'Bé' sản xuất bằng AI video.",
    model: 'Gemini Omni',
    duration: '1:00',
    language: 'en',
    rating: 5,
  },
  {
    id: 'commercial-coca-cola-tvc',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/coca-cola-tvc.mp4',
    poster: '/images/creative/coca-cola-tvc-poster.jpg',
    caption: 'Coca-Cola style commercial concept spot generated end-to-end with AI video.',
    captionVi: 'TVC concept phong cách Coca-Cola được tạo hoàn toàn bằng AI video.',
    model: 'Gemini Omni',
    duration: '1:00',
    language: 'vi',
    rating: 4,
  },
  {
    id: 'commercial-ads-gentadox-nanoshield',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/ads-gentadox-nanoshield.mp4',
    caption: 'Gentadox Nanoshield product ad — commercial-style AI-generated spot.',
    captionVi: 'Quảng cáo sản phẩm Gentadox Nanoshield — video commercial do AI tạo.',
    model: 'Veo 3.1',
    duration: '1:13',
    language: 'fil',
    rating: 5,
  },
  {
    id: 'commercial-construction-timelapse',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/construction-timelapse.mp4',
    caption: 'AI-generated construction timelapse commercial concept.',
    captionVi: 'Clip timelapse công trình do AI tạo — commercial.',
    model: 'Veo 3.1',
    duration: '0:24',
    language: 'vi',
    rating: 3,
  },
]

export const UGC_VIDEOS: CreativeItem[] = [
  {
    id: 'ugc-colgate',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/colgate-ugc.mp4',
    caption: 'Colgate UGC-style ad concept generated with AI video.',
    captionVi: 'Concept quảng cáo UGC cho Colgate do AI tạo.',
    model: 'Veo 3.1',
    duration: '0:32',
    language: 'vi',
    rating: 4,
  },
  {
    id: 'ugc-feb-04',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/feb-04-1428-15s.mp4',
    caption: 'AI-generated UGC concept clip.',
    captionVi: 'Clip UGC concept do AI tạo.',
    model: 'Veo 3.1',
    duration: '0:15',
    language: 'en',
    rating: 3,
  },
  {
    id: 'ugc-mans-sweating',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/the-mans-sweating.mp4',
    caption: 'AI-generated UGC lifestyle clip.',
    captionVi: 'Clip UGC lifestyle do AI tạo.',
    model: 'Veo 3.1',
    duration: '0:08',
    language: 'en',
    rating: 3,
  },
  {
    id: 'ugc-gucci-dress',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/gucci-dress-ugc.mp4',
    caption: 'Gucci dress UGC-style fashion concept generated with AI video.',
    captionVi: 'Concept UGC thời trang váy Gucci do AI tạo.',
    model: 'Veo 3.1',
    duration: '0:16',
    language: 'vi',
    rating: 5,
  },
  {
    id: 'ugc-new-gym-experience',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/ugc-new-gym-experience.mp4',
    caption: 'New gym experience UGC concept clip.',
    captionVi: 'Clip UGC trải nghiệm phòng gym mới.',
    model: 'Omni',
    duration: '0:20',
    language: 'vi',
    rating: 5,
  },
  {
    id: 'ugc-kling-motion-control',
    type: 'video',
    src: 'https://kwrnssd2wlpgmi3q.public.blob.vercel-storage.com/creative/kling-motion-control.mp4',
    caption: 'Motion-control UGC concept clip generated with Kling.',
    captionVi: 'Clip UGC motion-control tạo bằng Kling.',
    model: 'Kling',
    duration: '0:15',
    language: 'none',
    rating: 4,
  },
]
